#!/bin/bash
set -e

echo "Installing Ruby Dev Kit"

  apt-add-repository ppa:brightbox/ruby-ng
  apt-get update
  apt-get install -y ruby2.2 ruby2.2-dev

#echo "Installing Jenkins"

#  wget -q -O - https://jenkins-ci.org/debian/jenkins-ci.org.key | sudo apt-key add -
#  sh -c 'echo deb http://pkg.jenkins-ci.org/debian binary/ > /etc/apt/sources.list.d/jenkins.list'
#  apt-get update
#  apt-get -qy install jenkins

#  usermod -a -G vagrant jenkins
#  usermod -a -G jenkins vagrant
#  service jenkins start
#  sleep 240
#  java -jar /vagrant/.jenkins/jenkins-cli.jar -s http://localhost:8080 install-plugin git
#  java -jar /vagrant/.jenkins/jenkins-cli.jar -s http://localhost:8080 install-plugin xUnit
#  service jenkins restart

echo "Installing git command line tools"

  apt-get -qy install git
  echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

  #ln -s /vagrant/.jenkins/ /var/lib/jenkins

echo "Installing phantomjs"

  wget https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.7-linux-x86_64.tar.bz2
  mv phantomjs-1.9.7-linux-x86_64.tar.bz2 /usr/local/share/
  cd /usr/local/share/
  tar xvjf phantomjs-1.9.7-linux-x86_64.tar.bz2
  ln -sf /usr/local/share/phantomjs-1.9.7-linux-x86_64/bin/phantomjs /usr/bin/phantomjs

echo "Installing test Gems"

  apt-get install -y zlib1g-dev

  gem install cucumber
  gem install rspec
  gem install capybara
  gem install selenium-webdriver
  gem install poltergeist

echo "Installing Postgres and configuring remote connections"

  apt-get -qy install postgresql-9.3
  sed -i "s/#listen_addresses = 'localhost'/listen_addresses = '*'/g" /etc/postgresql/9.3/main/postgresql.conf
  sed -i "s/#host    replication     postgres        ::1\/128                 md5/host all all 0.0.0.0\/0 trust/g" /etc/postgresql/9.3/main/pg_hba.conf
  /etc/init.d/postgresql restart

  sudo apt-get install -y libpq-dev

  sudo -u postgres psql -p 5432 -c "ALTER USER postgres WITH PASSWORD 'admin';"

echo "Setting Up register Stub"

gem install sinatra
gem install rerun

cat <<EOF >> /etc/rc.local
  nohup ruby /home/vagrant/register-stub/run.rb >> log.txt 2>&1 &

EOF

cat <<EOF >> /etc/rc0.d/register-stub
#! /bin/sh
cd /home/vagrant
nohup ruby /home/vagrant/register-stub/run.rb >> log.txt 2>&1 &

EOF

nohup ruby /home/vagrant/register-stub/run.rb >> log.txt 2>&1 &

echo "Setting Up register Stub"

gem install sinatra
gem install rerun

cat <<EOF >> /etc/rc.local
  nohup ruby /home/vagrant/register-stub/run.rb >> log.txt 2>&1 &

EOF

cat <<EOF >> /etc/rc0.d/register-stub
#! /bin/sh
cd /home/vagrant
nohup ruby /home/vagrant/register-stub/run.rb >> log.txt 2>&1 &

EOF

nohup ruby /home/vagrant/register-stub/run.rb >> log.txt 2>&1 &

echo "Setting Up Test Site"


gem install sinatra
gem install pg
gem install rerun


sudo -u postgres psql -p 5432  << "EOF"
CREATE DATABASE test;

EOF
sudo -u postgres psql -p 5432 test << "EOF"
  CREATE DATABASE test;

  CREATE TABLE users (
    user_id  SERIAL PRIMARY KEY,
    user_name    varchar(40),
    user_password    varchar(40),
    user_status    integer
  );

EOF



cat <<EOF >> /etc/rc0.d/register-stub
#! /bin/sh
cd /home/vagrant
nohup ruby /home/vagrant/test-sinatra-website/run.rb >> log.txt 2>&1 &

EOF

nohup ruby /home/vagrant/test-sinatra-website/run.rb >> log.txt 2>&1 &
