#!/bin/bash
set -e

echo "Installing Ruby Dev Kit"

  apt-get install -y ruby1.9.1-dev

echo "Installing Jenkins"

  wget -q -O - https://jenkins-ci.org/debian/jenkins-ci.org.key | sudo apt-key add -
  sh -c 'echo deb http://pkg.jenkins-ci.org/debian binary/ > /etc/apt/sources.list.d/jenkins.list'
  apt-get update
  apt-get -qy install jenkins
  service jenkins start

echo "Installing git command line tools"

  apt-get -qy install git
  echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

echo "Installing Postgres and configuring remote connections"

  apt-get -qy install postgresql-9.3
  sed -i "s/#listen_addresses = 'localhost'/listen_addresses = '*'/g" /etc/postgresql/9.3/main/postgresql.conf
  sed -i "s/#host    replication     postgres        ::1\/128                 md5/host all all 0.0.0.0\/0 trust/g" /etc/postgresql/9.3/main/pg_hba.conf
  /etc/init.d/postgresql restart

  sudo apt-get install -y libpq-dev

  sudo -u postgres psql -p 5432 -c "ALTER USER postgres WITH PASSWORD 'admin';"

echo "Setting Up register Stub"

gem install sinatra
gem install rerun

cat <<EOF >> /etc/rc.local
  nohup ruby /home/vagrant/register-stub/run.rb >> log.txt 2>&1 &

EOF

cat <<EOF >> /etc/rc0.d/register-stub
#! /bin/sh
cd /home/vagrant
nohup ruby /home/vagrant/register-stub/run.rb >> log.txt 2>&1 &

EOF

nohup ruby /home/vagrant/register-stub/run.rb >> log.txt 2>&1 &

echo "Setting Up register Stub"

gem install sinatra
gem install rerun

cat <<EOF >> /etc/rc.local
  nohup ruby /home/vagrant/register-stub/run.rb >> log.txt 2>&1 &

EOF

cat <<EOF >> /etc/rc0.d/register-stub
#! /bin/sh
cd /home/vagrant
nohup ruby /home/vagrant/register-stub/run.rb >> log.txt 2>&1 &

EOF

nohup ruby /home/vagrant/register-stub/run.rb >> log.txt 2>&1 &

echo "Setting Up Test Site"


gem install sinatra
gem install pg
gem install rerun


sudo -u postgres psql -p 5432  << "EOF"
CREATE DATABASE test;

EOF
sudo -u postgres psql -p 5432 test << "EOF"
  CREATE DATABASE test;

  CREATE TABLE users (
    user_id  SERIAL PRIMARY KEY,
    user_name    varchar(40),
    user_password    varchar(40),
    user_status    integer
  );

EOF



cat <<EOF >> /etc/rc0.d/register-stub
#! /bin/sh
cd /home/vagrant
nohup ruby /home/vagrant/test-sinatra-website/run.rb >> log.txt 2>&1 &

EOF

nohup ruby /home/vagrant/test-sinatra-website/run.rb >> log.txt 2>&1 &
